# Generated by Django 3.2.16 on 2022-10-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_rename_post_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
